worktrees: make non-packed refs also work correctly.
Turns out aec58a9 did the right thing for /packed/ refs, but didn't work
correctly on /unpacked/ refs.  So this patch gives unpacked refs the
same treatment.

Without the fix here, the test added will cause this traceback:

======================================================================
ERROR: Check that we find .git as a worktree file and find the worktree
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pjones/devel/github.com/GitPython/git/test/lib/helper.py", line 92, in wrapper
    return func(self, path)
  File "/home/pjones/devel/github.com/GitPython/git/test/test_repo.py", line 938, in test_git_work_tree_dotgit
    self.assertIsInstance(repo.heads['aaaaaaaa'], Head)
  File "/home/pjones/devel/github.com/GitPython/git/util.py", line 893, in __getitem__
    raise IndexError("No item found with id %r" % (self._prefix + index))
IndexError: No item found with id 'aaaaaaaa'

Woops.

Things I've learned:
- test_remote doesn't work currently if you start on a branch.  I think
  it never did?
- Because of 346424da, all *sorts* of stuff in the test suite doesn't
  work if you name your development branch "packed-refs"
  (This seems like a bug...)

Signed-off-by: Peter Jones <pjones@redhat.com>