Try to ignore test on windows as it fails for the wrong reasons
Here is the error log we see:

======================================================================
ERROR: test_git_submodules_and_add_sm_with_new_commit (git.test.test_submodule.TestSubmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\gitpython\git\test\lib\helper.py", line 92, in wrapper
    return func(self, path)
  File "C:\projects\gitpython\git\test\test_submodule.py", line 709, in test_git_submodules_and_add_sm_with_new_commit
    smm.git.commit(m="new file added")
  File "C:\projects\gitpython\git\cmd.py", line 425, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\projects\gitpython\git\cmd.py", line 877, in _call_process
    return self.execute(call, **exec_kwargs)
  File "C:\projects\gitpython\git\cmd.py", line 688, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git commit -m new file added
  stderr: '
*** Please tell me who you are.