BF: remove ddt from requirements.txt since no ddt required at run time.
Otherwise, since requirements.txt is loaded into install_requires, any installation
which manages to miss installing ddt could cause setuptools to freak out.
E.g.

here is a traceback from running tests of datalad

    ======================================================================
    ERROR: datalad.metadata.tests.test_aggregation.test_update_strategy
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/yoh/anaconda-2018.12-3.7/envs/test-gitpython/lib/python3.7/site-packages/datalad/metadata/metadata.py", line 511, in _get_metadata
        extractor_cls = extractors[mtype_key].load()
      File "/home/yoh/anaconda-2018.12-3.7/envs/test-gitpython/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2442, in load
        self.require(*args, **kwargs)
      File "/home/yoh/anaconda-2018.12-3.7/envs/test-gitpython/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/home/yoh/anaconda-2018.12-3.7/envs/test-gitpython/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The "ddt>=1.1.1" distribution was not found and is required by GitPython

in conda environment.  Original commit 74a0507f4eb468b842d1f644f0e43196cda290a1
which added ddt there unfortunately does not state the reason so probably was
just a slip