Fuzzing: Gracefully Handle Uninteresting Error to Fix OSS-Fuzz Issue 71095
Fuzzing data can generate filenames that trigger:
> OSError: [Errno 36] File name too long

The changes here add handling for these exceptions because they di not
indicate a bug and should not crash the fuzzer.
a