Maybe work around AppVeyor setting a bad email?
One of the submodule tests says:

Traceback (most recent call last):
  File "C:\projects\gitpython\git\test\lib\helper.py", line 92, in wrapper
    return func(self, path)
  File "C:\projects\gitpython\git\test\test_submodule.py", line 706, in test_git_submodules_and_add_sm_with_new_commit
    smm.git.commit(m="new file added")
  File "C:\projects\gitpython\git\cmd.py", line 425, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\projects\gitpython\git\cmd.py", line 877, in _call_process
    return self.execute(call, **exec_kwargs)
  File "C:\projects\gitpython\git\cmd.py", line 688, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git commit -m new file added
  stderr: '
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'appveyor@APPVYR-WIN.(none)')'

Clearly this is failing because (none) isn't a valid TLD, but I figure
I'll try to set a fake value and see if that works around it.