config: FIX regression by prev commit "wrap all conf..."
+ Bug appeared as last 5 TCs (test_commit & test_stream) said:

  OSError: [WinError 6] The handle is invalid